---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: maven:3-jdk-8-slim
  commands:
    - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    # - ./mvnw test -B
